name: Deploy to EC2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure SSH Key
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          scp  -o StrictHostKeyChecking=no -P 109 -r ~/test ubuntu@stage2.aqucloud.com:/home/ubuntu/deployment
          ssh  -o StrictHostKeyChecking=no -p 109 ubuntu@stage2.aqucloud.com 'cd /home/ubuntu/deployment && touch a b'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
