name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
      target_branch:
        description: 'Branch to deploy'
        required: false
        default: 'main'

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4 
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key -P 109 -r ./*  ubuntu@stage2.aqucloud.com:/home/ubuntu/deployment
          ssh -o StrictHostKeyChecking=no -i private_key -p 109 ubuntu@stage2.aqucloud.com '
            # Now we have got the access of EC2 and we will start the deploy.
            cd /home/ubuntu/deployment &&
            touch "$(date '+%Y-%m-%d_%H-%M-%S')" &&
            rm private_key
          '
