name: Deploy to EC2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_KEY_PATH: ${{ github.workspace }}/private.key

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $SSH_KEY_PATH
          sudo chmod 600 $SSH_KEY_PATH
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          scp -i $SSH_KEY_PATH -o StrictHostKeyChecking=no -P 109 -r ~/test ubuntu@stage2.aqucloud.com:/home/ubuntu/deployment
          ssh -i $SSH_KEY_PATH -o StrictHostKeyChecking=no -p 109 ubuntu@stage2.aqucloud.com 'cd /path/to/deployment && touch abc' 
	env:
 	SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  	SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
