name: Deploy


on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
        run: |
          
          scp -o StrictHostKeyChecking=no -i <(echo "$PRIVATE_KEY")  -P 108 -r ./*  ubuntu@43.205.243.195:/home/ubuntu/deployment
          ssh -o StrictHostKeyChecking=no -i <(echo "$PRIVATE_KEY")  -p 108 ubuntu@43.205.243.195 '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/deployment &&
              touch absnas 
              '
